### ISSUE TITLE
Can we use preload function in client side render?

### ISSUE THREAD

**Issue by leo6104** [ngx-lottie/ngx-lottie#40]
## I'm submitting a...

<pre><code>
[x] Performance issue
[x] Feature request
</code></pre>

## Current behavior

It seems only have 'cache' & server-side preload strategy. 

## Expected behavior

Suggest interface like below
```
@NgModule({
    imports: [ 
       LottieClientPreloadModule.forRoot({ 
            preloadAnimations: {
               folder: 'dist/assets',
               animations: ['data.json']
            }
       }) 
    ]
})
export class AppModule 
```

## What is the motivation / use case for changing the behavior?

In 3G Network speed, preloading all json in background can be helpful to improve user experience.

**Comment by arturovt** [comment]
IMO this is out of scope for this package since its purpose is only to render animation.

If by the word "preload" you mean the "earlier fetch" (`link[preload]`) then you actually can specify them directly in your `index.html`:
```html
<link rel="preload" href="/assets/animation.json" as="fetch" />
```

Either you provide JSON file names in the module options, or you provide them in your `index.html`.
