### ISSUE TITLE
Dynamic loading of options is not detected

### ISSUE THREAD

**Issue by apoorvaravi** [ngx-lottie/ngx-lottie#48]
## I'm submitting a...
<pre><code>
[ ] Other... Please describe: How to load multiple animation files with different options with in the same ng-lottie, So basically i want to play one animation once the newer animation arrives, it should start planning the latest one, 
</code></pre>

## Current behavior
With one ng-lottie tag, the newer animations are not played, it always plays the older animation when options are changed

## Expected behavior
Should allow new animations to be played when options change,

## Minimal reproduction of the problem with instructions

* Step 1: Set options in ngOnint of the component.
* Step 2: Reset options again when changed in ngOnchanges
* Step 3: The options with changes are not displayed
Change detetion on options is not triggered and so the changed options are not rendered

## What is the motivation / use case for changing the behavior?
Play animations dynamically

## Environment

Libs:
- @angular/core version: 8 and 9
- ngx-lottie version: latest

Browser:
- [ ] Chrome (desktop) version latest

 
For Tooling issues:
- Node version: 6.9
- Platform:  MAC

**Comment by arturovt** [comment]
The current behavior is expected because there is no way to update options in the `lottie-web` library. From the user perspective, I've seen that all animations are static and `path` or `animationData` never changes.

Tracking options, especially those properties that can really change will be performance-sensitive and it's not a target of that framework.

It can be kept out of the framework, Angular provides a lot of tools to solve different tasks. You can create some kind of wrapper over `ng-lottie` that will re-create the component every time when options change.
