### ISSUE TITLE
Action inside of complete event does not perform correctly

### ISSUE THREAD

**Issue by andriyor** [ngx-lottie/ngx-lottie#58]
Sorry for my english

## I'm submitting a...

I don't know it's bug in library or I didn't fully understand Angular 

- [x] Bug report  

## Current behavior

When i click on second button occurs calling mock service that after finish disables button and its ok
on first implementation, button should be disabled after complete event 
But it disabled only after click outside of button

## Expected behavior

First button should be disabled after complete event

## Minimal reproduction of the problem with instructions

![Peek 2020-06-16 17-46](https://user-images.githubusercontent.com/11459840/84790804-718d6c80-affa-11ea-80a7-36d50eda417a.gif)

## Environment
I prepared project that reproduces this bug
https://github.com/andriyor/ngx-lottie-demo

Browser:
- [x] Chrome (desktop) version 83

**Comment by arturovt** [comment]
Thanks for reproduction, I'll check it asap.

**Comment by arturovt** [comment]
Yep, it's an issue since this async task is queued and invoked in the root context which Angular is unaware of. Thus it doesn't run change detection.

I will provide a fix soon.

**Comment by arturovt** [comment]
One of the temporary workarounds is to notify Angular's zone that something has happened by doing this:
```ts
onComplete() {
  this.ngZone.run(() => (this.buttonIsDisabled = true));
}
```

**Comment by arturovt** [comment]
Umm, I've actually remembered why this design decision was made. Animation items can emit hundreds and thousands of events every second depending on what event you listen to.

Some events are not synchronous because they're wrapped into `setTimeout` inside of the `lottie-web` library. This means that if thousand of event occurs during the single second then Angular will run change detection thousand times, which will drastically decrease performance.

This behaviour should be documented as well. I will update the readme.
