### ISSUE TITLE
Angular Ivy Support

### ISSUE THREAD

**Issue by ThePatzen** [ngx-lottie/ngx-lottie#67]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When i Build an angular app using ivy i get the following error:

`Warning: Invalid constructor parameter decorator in xxx/node_modules/ngx-lottie/fesm2015/ngx-lottie.js:
 () => [
    { type: NgZone },
    { type: String, decorators: [{ type: Inject, args: [PLATFORM_ID,] }] },
    { type: undefined, decorators: [{ type: Inject, args: [LOTTIE_OPTIONS,] }] },
    { type: undefined, decorators: [{ type: Inject, args: [ANIMATION_CACHE,] }] }
]
Error: Error on worker #6: Error: getInternalNameOfClass() called on a non-ES5 class: expected AnimationLoader to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass `

## Expected behavior

This should work :-)

## Environment

<pre><code>
Libs:
- @angular/core version: 9.1.12
- ngx-lottie version: 6.3.0

Please help :-)

Best Regards from austria!
David

**Comment by arturovt** [comment]
Could you provide a minimal reproducible example? The current repository has Ivy enabled.

**Comment by ThePatzen** [comment]
Hi!

I found out that changing the build-target from esm5 to es2015 everything works fine. Seems a Problem with the esm5 target settings!

Best Regards!

**Comment by arturovt** [comment]
I've seen that people observed the same issue in their apps considering issues on Angular's github and they all were opened recently. Prolly some breaking change was introduced but I can't say what exactly is. Don't forget that you will need to enable differential loading when you change the `target` to `es2015` since ES5-compatible code will not be served anymore until you provide appropriate browsers in the `.browserlist`.
